// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/exchange-max-session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/exchange-max-session.post').default>>>>
    }
    '/api/auth/exchange-telegram-session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/exchange-telegram-session.post').default>>>>
    }
    '/api/auth/exchange-vk-session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/exchange-vk-session.post').default>>>>
    }
    '/api/auth/link-max': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/link-max.post').default>>>>
    }
    '/api/auth/link-telegram': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/link-telegram.post').default>>>>
    }
    '/api/auth/max-link-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/max-link-status.get').default>>>>
    }
    '/api/auth/request-max-link': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/request-max-link.post').default>>>>
    }
    '/api/auth/request-telegram-link': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/request-telegram-link.post').default>>>>
    }
    '/api/auth/request-vk-link': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/request-vk-link.post').default>>>>
    }
    '/api/auth/telegram-link-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/telegram-link-status.get').default>>>>
    }
    '/api/auth/vk-id/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/vk-id/callback.get').default>>>>
    }
    '/api/auth/vk-link-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/vk-link-status.get').default>>>>
    }
    '/api/cities': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cities.get').default>>>>
    }
    '/api/cities/:slug/events/:eventSlug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cities/[slug]/events/[eventSlug].get').default>>>>
    }
    '/api/cities/:slug/events': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cities/[slug]/events/index.get').default>>>>
    }
    '/api/cities/:slug/home': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cities/[slug]/home.get').default>>>>
    }
    '/api/cities/:slug/stories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cities/[slug]/stories.get').default>>>>
    }
    '/api/cities/:slug/venues/:venueSlug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cities/[slug]/venues/[venueSlug].get').default>>>>
    }
    '/api/cities/:slug/venues': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cities/[slug]/venues/index.get').default>>>>
    }
    '/api/client-orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/client-orders.get').default>>>>
    }
    '/api/cron/review-prompts': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/review-prompts.post').default>>>>
    }
    '/api/dashboard/access': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/access.get').default>>>>
    }
    '/api/dashboard/branches': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/branches.post').default>>>>
    }
    '/api/dashboard/branches/:id': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/branches/[id].put').default>>>>
    }
    '/api/dashboard/branches/:id/deactivate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/branches/[id]/deactivate.post').default>>>>
    }
    '/api/dashboard/features': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/features.get').default>>>>
    }
    '/api/dashboard/features/toggle': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/features/toggle.post').default>>>>
    }
    '/api/dashboard/integrations/festival-moderation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/integrations/festival-moderation.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/integrations/festival-moderation.put').default>>>>
    }
    '/api/dashboard/integrations/festival-moderation/test': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/integrations/festival-moderation/test.post').default>>>>
    }
    '/api/dashboard/integrations/max-chat-link-token': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/integrations/max-chat-link-token.post').default>>>>
    }
    '/api/dashboard/integrations/notification-events': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/integrations/notification-events.get').default>>>>
    }
    '/api/dashboard/integrations/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/integrations/notifications.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/integrations/notifications.put').default>>>>
    }
    '/api/dashboard/integrations/notifications/test': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/integrations/notifications/test.post').default>>>>
    }
    '/api/dashboard/integrations/telegram-chat-link-token': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/integrations/telegram-chat-link-token.post').default>>>>
    }
    '/api/dashboard/integrations/telegram-chat-unlink': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/integrations/telegram-chat-unlink.post').default>>>>
    }
    '/api/dashboard/moderation/city-ugc': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/moderation/city-ugc.get').default>>>>
    }
    '/api/dashboard/moderation/city-ugc/action': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/moderation/city-ugc/action.post').default>>>>
    }
    '/api/dashboard/orders/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/orders/[id].get').default>>>>
    }
    '/api/dashboard/orders/:id/delay': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/orders/[id]/delay.post').default>>>>
    }
    '/api/dashboard/orders/:id/review-prompt': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/orders/[id]/review-prompt.post').default>>>>
    }
    '/api/dashboard/orders/:id/status': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/orders/[id]/status.put').default>>>>
    }
    '/api/dashboard/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/orders/index.get').default>>>>
    }
    '/api/dashboard/organization/media': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/organization/media.post').default>>>>
    }
    '/api/dashboard/organization/style-presets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/organization/style-presets.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/organization/style-presets.post').default>>>>
    }
    '/api/dashboard/organization/style': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/organization/style.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/organization/style.put').default>>>>
    }
    '/api/dashboard/organization/style/contacts': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/organization/style/contacts.put').default>>>>
    }
    '/api/dashboard/organization/style/identity': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/organization/style/identity.put').default>>>>
    }
    '/api/dashboard/organization/style/operations': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/organization/style/operations.put').default>>>>
    }
    '/api/dashboard/organization/style/rollback': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/organization/style/rollback.post').default>>>>
    }
    '/api/dashboard/organization/style/styles': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/organization/style/styles.put').default>>>>
    }
    '/api/dashboard/restaurants': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/restaurants.get').default>>>>
    }
    '/api/dashboard/reviews/action': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/reviews/action.post').default>>>>
    }
    '/api/dashboard/reviews': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/reviews/index.get').default>>>>
    }
    '/api/dashboard/storefront': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/storefront.get').default>>>>
    }
    '/api/dashboard/stories/campaigns/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/stories/campaigns/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/stories/campaigns/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/stories/campaigns/[id].put').default>>>>
    }
    '/api/dashboard/stories/campaigns': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/stories/campaigns/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/stories/campaigns/index.post').default>>>>
    }
    '/api/dashboard/stories/media.upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/stories/media.upload.post').default>>>>
    }
    '/api/festival/:festival_slug/achievements': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/festival/[festival_slug]/achievements.get').default>>>>
    }
    '/api/festival/:festival_slug/reviews': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/festival/[festival_slug]/reviews.post').default>>>>
    }
    '/api/festival/:festival_slug/ugc': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/festival/[festival_slug]/ugc.get').default>>>>
    }
    '/api/festival/:festival_slug/ugc/eligibility': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/festival/[festival_slug]/ugc/eligibility.get').default>>>>
    }
    '/api/festival/:festival_slug/ugc/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/festival/[festival_slug]/ugc/upload.post').default>>>>
    }
    '/api/geocode': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/geocode.get').default>>>>
    }
    '/api/platform-cities': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/platform-cities.get').default>>>>
    }
    '/api/reviews': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reviews.get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reviews.patch').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reviews.post').default>>>>
    }
    '/api/shops': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shops.get').default>>>>
    }
    '/api/stories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stories.get').default>>>>
    }
    '/api/stories/views': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stories/views.post').default>>>>
    }
    '/api/tenant': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tenant.get').default>>>>
    }
    '/api/tenant/cities': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tenant/cities.get').default>>>>
    }
    '/api/tenant/resolve-canonical': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tenant/resolve-canonical.get').default>>>>
    }
    '/api/webhook-max': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhook-max.post').default>>>>
    }
    '/api/webhook-relay': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhook-relay.post').default>>>>
    }
    '/api/webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhook.post').default>>>>
    }
    '/api/webhooks/yookassa': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhooks/yookassa.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}