// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/25/2026, 7:21:03 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/arsalanbaranzaev/Desktop/projects/incity-new/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arsalanbaranzaev/Desktop/projects/incity-new/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arsalanbaranzaev/Desktop/projects/incity-new/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arsalanbaranzaev/Desktop/projects/incity-new/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arsalanbaranzaev/Desktop/projects/incity-new/plugins/**/*.{js,ts,mjs}","/Users/arsalanbaranzaev/Desktop/projects/incity-new/composables/**/*.{js,ts,mjs}","/Users/arsalanbaranzaev/Desktop/projects/incity-new/utils/**/*.{js,ts,mjs}","/Users/arsalanbaranzaev/Desktop/projects/incity-new/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arsalanbaranzaev/Desktop/projects/incity-new/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/arsalanbaranzaev/Desktop/projects/incity-new/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/arsalanbaranzaev/Desktop/projects/incity-new/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;