-- Fluent Emoji 3D pack (MIT) — PNG stickers for carousel editor

insert into public.stickers (category, name, description, tags, image_url, is_vector, accent_recolorable, sort_order)
select
  'emoji',
  v.name,
  v.description,
  v.tags,
  v.image_url,
  false,
  false,
  v.sort_order
from (values
  ('fire', 'Fire hype', array['hot','hype','popular','fire'], '/carousel-stickers/emoji/emoji_fire.png', 1),
  ('party_popper', 'Party celebration', array['party','club','dance','balloon'], '/carousel-stickers/emoji/emoji_party_popper.png', 2),
  ('geo_pin', 'Location pin', array['location','map','venue','geo_pin'], '/carousel-stickers/emoji/emoji_round_pushpin.png', 3),
  ('tickets', 'Event tickets', array['ticket','concert','cinema','tickets'], '/carousel-stickers/emoji/emoji_admission_tickets.png', 4),
  ('music', 'Music', array['music','concert','dj','mic'], '/carousel-stickers/emoji/emoji_musical_note.png', 5),
  ('clapperboard', 'Cinema', array['cinema','movie','clapperboard'], '/carousel-stickers/emoji/emoji_clapper_board.png', 6),
  ('masks', 'Theatre', array['theatre','comedy','masks'], '/carousel-stickers/emoji/emoji_performing_arts.png', 7),
  ('mic', 'Microphone', array['concert','music','karaoke','mic'], '/carousel-stickers/emoji/emoji_microphone.png', 8),
  ('palette', 'Art palette', array['art','exhibition','palette'], '/carousel-stickers/emoji/emoji_artist_palette.png', 9),
  ('lightbulb', 'Idea workshop', array['lecture','business','workshop','lightbulb'], '/carousel-stickers/emoji/emoji_light_bulb.png', 10),
  ('sneaker', 'Sport run', array['sport','run','sneaker'], '/carousel-stickers/emoji/emoji_running_shoe.png', 11),
  ('balloon', 'Kids party', array['kids','family','balloon','party'], '/carousel-stickers/emoji/emoji_balloon.png', 12),
  ('heart', 'Love heart', array['heart','romance','love'], '/carousel-stickers/emoji/emoji_red_heart.png', 13),
  ('star', 'Star highlight', array['star','top','featured'], '/carousel-stickers/emoji/emoji_glowing_star.png', 14),
  ('wine', 'Wine glass', array['wine','gastro','bar'], '/carousel-stickers/emoji/emoji_wine_glass.png', 15),
  ('camera', 'Camera photo', array['photo','exhibition','camera'], '/carousel-stickers/emoji/emoji_camera.png', 16),
  ('users', 'Group friends', array['family','friends','group'], '/carousel-stickers/emoji/emoji_busts_in_silhouette.png', 17),
  ('zap', 'Energy bolt', array['energy','fast','zap'], '/carousel-stickers/emoji/emoji_high_voltage.png', 18),
  ('sun', 'Sunny outdoor', array['sun','outdoor','summer'], '/carousel-stickers/emoji/emoji_sun.png', 19),
  ('moon', 'Nightlife moon', array['night','nightlife','moon'], '/carousel-stickers/emoji/emoji_crescent_moon.png', 20),
  ('utensils', 'Restaurant food', array['food','restaurant','gastro'], '/carousel-stickers/emoji/emoji_fork_and_knife.png', 21),
  ('beer', 'Beer pub', array['beer','bar','pub'], '/carousel-stickers/emoji/emoji_beer_mug.png', 22),
  ('tree', 'Park nature', array['park','nature','outdoor'], '/carousel-stickers/emoji/emoji_deciduous_tree.png', 23),
  ('bike', 'Cycling', array['bike','sport','cycling'], '/carousel-stickers/emoji/emoji_bicycle.png', 24),
  ('baby', 'Kids family', array['kids','family','baby'], '/carousel-stickers/emoji/emoji_baby.png', 25),
  ('graduation', 'Education', array['lecture','education','school'], '/carousel-stickers/emoji/emoji_graduation_cap.png', 26),
  ('building', 'Venue building', array['venue','building','mall'], '/carousel-stickers/emoji/emoji_office_building.png', 27),
  ('car', 'Car parking', array['car','parking','drive'], '/carousel-stickers/emoji/emoji_automobile.png', 28),
  ('plane', 'Travel flight', array['travel','plane','tourism'], '/carousel-stickers/emoji/emoji_airplane.png', 29),
  ('train', 'Train metro', array['train','transport','metro'], '/carousel-stickers/emoji/emoji_high_speed_train.png', 30),
  ('bus', 'Bus transport', array['bus','transport'], '/carousel-stickers/emoji/emoji_bus.png', 31),
  ('phone', 'Phone booking', array['phone','booking','call'], '/carousel-stickers/emoji/emoji_mobile_phone.png', 32),
  ('globe', 'Web tourism', array['web','globe','tourism'], '/carousel-stickers/emoji/emoji_globe.png', 33),
  ('gift', 'Gift holiday', array['gift','holiday','present'], '/carousel-stickers/emoji/emoji_wrapped_gift.png', 34),
  ('croissant', 'Bakery cafe', array['bakery','breakfast','cafe'], '/carousel-stickers/emoji/emoji_croissant.png', 35),
  ('headphones', 'Podcast music', array['music','podcast','headphones'], '/carousel-stickers/emoji/emoji_headphone.png', 36),
  ('video', 'Video stream', array['video','stream','online'], '/carousel-stickers/emoji/emoji_video_camera.png', 37),
  ('hundred', 'Perfect hype', array['hype','top','perfect'], '/carousel-stickers/emoji/emoji_hundred_points.png', 38),
  ('thumbs_up', 'Recommend like', array['like','recommend','thumbs_up'], '/carousel-stickers/emoji/emoji_thumbs_up.png', 39),
  ('sparkles', 'Sparkles decor', array['sparkle','magic','decor'], '/carousel-stickers/emoji/emoji_sparkles.png', 40),
  ('calendar', 'Calendar date', array['date','schedule','calendar'], '/carousel-stickers/emoji/emoji_calendar.png', 41),
  ('clock', 'Time schedule', array['time','schedule','clock'], '/carousel-stickers/emoji/emoji_alarm_clock.png', 42),
  ('price_tag', 'Price label', array['price','money','price_tag'], '/carousel-stickers/emoji/emoji_label.png', 43),
  ('exclamation', 'Important alert', array['important','alert','exclamation'], '/carousel-stickers/emoji/emoji_exclamation.png', 44),
  ('coffee_cup', 'Coffee brunch', array['weekend','brunch','cafe','coffee_cup'], '/carousel-stickers/emoji/emoji_hot_beverage.png', 45),
  ('bookmark', 'Save favorite', array['save','favorite','bookmark'], '/carousel-stickers/emoji/emoji_bookmark.png', 46),
  ('paper_plane', 'Share repost', array['share','repost','paper_plane'], '/carousel-stickers/emoji/emoji_paper_airplane.png', 47),
  ('partying', 'Party face', array['party','fun','celebration'], '/carousel-stickers/emoji/emoji_partying_face.png', 48),
  ('eyes', 'Look here', array['attention','look','swipe'], '/carousel-stickers/emoji/emoji_eyes.png', 49),
  ('confetti', 'Confetti', array['party','celebration','confetti'], '/carousel-stickers/emoji/emoji_confetti_ball.png', 50)
) as v(name, description, tags, image_url, sort_order)
where not exists (
  select 1 from public.stickers s where s.image_url = v.image_url
);
